
services:
  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wp_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-bsccns}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:php8.2-apache
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-bsccns}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
    volumes:
      - ./_data:/var/www/html
    ports:
      - "8080:80"

  wpcli:
    image: wordpress:cli-php8.2
    depends_on:
      db:
        condition: service_healthy
    working_dir: /var/www/html
    entrypoint: ["wp"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-bsccns}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WP_CLI_CONFIG_PATH: /dev/null
    volumes:
      - ./_data:/var/www/html
volumes:
  db_data:
